version: "3"
services:
  app:
    build: .
    volumes:
      - ./:/work:cached
      - ~/gocache:/gocache
      - ~/gomodcache:/gomodcache
    working_dir: /hello
    environment:
      - BUILDKITE_AGENT_ACCESS_TOKEN
      - BUILDKITE_JOB_ID
      - BUILDKITE_BUILD_ID
      - BUILDKITE_BUILD_NUMBER
      - GOCACHE=/gocache
      - GOMODCACHE=/gomodcache
