env:
  PATH: "\\$PATH:/usr/local/go/bin"

steps:
  - block: "Input"
    prompt: "Enter your name:"
    fields:
    - text: "What is your name?"
      key: "name"
      
  - command: "/bin/chmod +x /var/lib/buildkite-agent/builds/ip-172-31-23-99-ec2-internal-1/nizarc-buildkite-demo/buildkite-demo-app/.buildkite/script.sh"
    label: "Set permissions"
  - command: "/var/lib/buildkite-agent/builds/ip-172-31-23-99-ec2-internal-1/nizarc-buildkite-demo/buildkite-demo-app/.buildkite/script.sh"
    artifact_paths:
    - 'dist/app' # upload the built application as an artifact
    plugins:
      - docker-compose#v5.4.0:
        run: app
    label: "Build & Execute app"
  
    #env:
      #name: "Nizar"
