steps:
  - label: ":docker: Build Project"
    plugins:
    - docker#v3.9.0:
          image: "golang:1.18.0"
          workdir: "/app"
          volumes:
            - ".:/app"
    command:
      - go build -o hello/hello ./hello
    artifact_paths:
      - "hello/hello"
  - label: ":question: Enter Name"
    type: block
    prompt: "What is your name?"
    fields:
      - text: "Your name"
        key: "name"
  - label: ":large_green_circle: Running Hello Go program"
    command:
      - buildkite-agent artifact download "hello/hello" .
      - chmod +x hello/hello
      - ./hello/hello $(buildkite-agent meta-data get "name")
        # Executes the binary, passing the user's name retrieved from metadata as an argument.
