env:
  PATH: "\\$PATH:/usr/local/go/bin"

steps:
  - input: "Information please"
    fields:
      - text: "What is your name?"
        key: "name"


  - command: "/bin/chmod +x /var/lib/buildkite-agent/builds/ip-172-31-23-99-ec2-internal-1/nizarc-buildkite-demo/buildkite-demo-app/.buildkite/script.sh\n\n/var/lib/buildkite-agent/builds/ip-172-31-23-99-ec2-internal-1/nizarc-buildkite-demo/buildkite-demo-app/.buildkite/script.sh"
    label: "Build app"
    #env:
      #name: "Nizar"
